### ISSUE TITLE
Code avec style

### ISSUE THREAD

**Issue by greut** [SylvainRamseyer/MeteorSiege#1]
Pour vous éviter les surprises quand vous passerez sur un système un peu plus strict vis-à-vis de la casse de vos fichiers.

> _Package names are all lowercase, with consecutive words simply concatenated together (no underscores). For example, `com.example.deepspace`, not `com.example.deepSpace` or `com.example.deep_space`._
> 
> https://google.github.io/styleguide/javaguide.html

Et ceci aussi. Car un bon IDE est sensé vous fournir ce type d'information-là.

> _Do not create formatted blocks of asterisks around comments._
> 
> https://msdn.microsoft.com/en-us/library/ff926074.aspx

**Comment by axelroy** [comment]
On avait fait la remarque lorsqu'on a fait revu le code de refonte effectué cet après midi, nous avons cette bonne pratique en tête. Merci pour le commentaire, correction dans l'heure à venir.

Intéressant pour les commentaires, nous y penserons.

Merci pour les remarques constructives!

**Comment by greut** [comment]
Intégration avec Eclipse :
- http://checkstyle.sourceforge.net/google_style.html
- http://eclipse-cs.sourceforge.net/

**Comment by axelroy** [comment]
Merci !
